# Generated by Django 4.2.7 on 2024-11-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='occupation',
            field=models.CharField(choices=[('dg', 'Directeur Général'), ('dga', 'Directrice Générale Adjointe'), ('chef_departement', 'Chef de département'), ('chef_cellule', 'Chef de cellule'), ('charge_etude', "Charger d'étude"), ('communication', 'Communication'), ('logistique', 'Logistique'), ('comptabilite', 'Comptabilité'), ('rh', 'RH'), ('secretaire', 'Secrétaire'), ('agoa', 'Agoa'), ('visiteur', 'Visiteur')], default='other', max_length=150, verbose_name='Occupation'),
        ),
    ]
