# Generated by Django 4.2.7 on 2024-11-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_alter_user_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='entreprise',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='motif',
            field=models.TextField(blank=True, null=True, verbose_name='Motif de la visite'),
        ),
        migrations.AlterField(
            model_name='user',
            name='occupation',
            field=models.CharField(choices=[('dg', 'Directeur Général'), ('dga', 'Directrice Générale Adjointe'), ('chef_departement', 'Chef de département'), ('chef_cellule', 'Chef de cellule'), ('charge_etude', "Charger d'étude"), ('communication', 'Communication'), ('logistique', 'Logistique'), ('comptabilite', 'Comptabilité'), ('rh', 'RH'), ('secretaire', 'Secrétaire'), ('agoa', 'Agoa'), ('visiteur', 'Visiteur'), ('visil', 'Visil')], default='other', max_length=150, verbose_name='Occupation'),
        ),
    ]
