# Generated by Django 4.2.7 on 2024-11-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_profile_entreprise_profile_motif_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='motif',
        ),
        migrations.AddField(
            model_name='user',
            name='entreprise',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='motif',
            field=models.TextField(blank=True, null=True, verbose_name='Motif de la visite'),
        ),
    ]
