# Generated by Django 4.2.7 on 2024-11-15 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0006_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='motif',
        ),
    ]
