# Generated by Django 4.2.7 on 2025-02-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0007_remove_user_motif'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cellule',
            field=models.CharField(choices=[('cellule_partenariat', 'Cellule Partenariat'), ('cellule_etude_marche', 'Cellule Etude et Marché'), ('cellule_evenementiel', 'Cellule Evenementiel'), ('cellule_etude_analyse_donnee', 'Cellule Etudes et Analyses des Données'), ('cellule_documentation_archive', 'Cellule Documentation et Archives'), ('cellule_certification', 'Cellule Certification'), ('cellule_reglementation', 'Cellule Reglementation'), ('agent_comptable', 'Agent Comptable'), ('service_rh', 'Service des ressources humaines'), ('service_logistique', 'Service Logistique'), ('service_com_rp', 'Service Communication et Relations Publiques'), ('secretariat_central', 'Secrétariat Central'), ('controlleur_financier', 'Contrôleur Financier'), ('autre', 'Autre')], default='autre', max_length=150, verbose_name='Cellule'),
        ),
        migrations.AddField(
            model_name='user',
            name='departement',
            field=models.CharField(choices=[('certification_reglementation', 'Certification et Reglementation'), ('marketing', 'Marketing'), ('statistique_documentation', 'Statistique et Documentation'), ('autre', 'Autre')], default='autre', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(choices=[('chef_cellule', 'Chef Cellule'), ('chef_service', 'Chef Service'), ('autre', 'Autre')], default='autre', max_length=150, verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='occupation',
            field=models.CharField(choices=[('dg', 'Directeur Général'), ('dga', 'Directrice Générale Adjointe'), ('chef_departement', 'Chef de département'), ('chef_cellule', 'Chef de cellule'), ('charge_etude', "Charger d'étude"), ('communication', 'Communication'), ('logistique', 'Logistique'), ('comptabilite', 'Comptabilité'), ('rh', 'RH'), ('secretaire', 'Secrétaire'), ('agoa', 'Agoa'), ('conseiller', 'Conseiller'), ('saf', 'SAF'), ('visiteur', 'Visiteur'), ('visil', 'Visil'), ('autre', 'Autre')], default='other', max_length=150, verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, verbose_name="Nom d'utilisateur"),
        ),
    ]
