# Generated by Django 4.2.7 on 2025-04-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0009_remove_profile_image_profile_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('marketing', 'Marketing'), ('certification', 'Certification'), ('communication', 'Communication'), ('statistique', 'Statistique'), ('logistique', 'Logistique'), ('rh', 'RH'), ('autre', 'Autre')], default='autre', max_length=150, verbose_name='Rôle'),
        ),
    ]
