# Generated by Django 4.2.7 on 2025-06-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0010_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='est_employer',
            field=models.BooleanField(default=True),
        ),
    ]
