# Generated by Django 4.2.7 on 2025-06-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0011_user_est_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='est_employer',
            field=models.BooleanField(default=False),
        ),
    ]
