# Generated by Django 4.2.7 on 2025-06-25 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationConventionnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('publier', 'Publier')], default='brouillon', max_length=10)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Est supprimé')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Certificat Conventionnel',
            },
        ),
        migrations.CreateModel(
            name='CertificationTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('publier', 'Publier')], default='brouillon', max_length=10)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Est supprimé')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Certificat Technique',
            },
        ),
        migrations.CreateModel(
            name='ProcedureGlobale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('publier', 'Publier')], default='brouillon', max_length=10)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Est supprimé')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Procédure Global',
            },
        ),
        migrations.AlterModelOptions(
            name='motdirecteur',
            options={'verbose_name': 'Mot du DG', 'verbose_name_plural': 'Mot du DG'},
        ),
        migrations.AlterModelOptions(
            name='quisommenous',
            options={'verbose_name_plural': 'Qui sommes nous ?'},
        ),
        migrations.AlterModelOptions(
            name='visionmission',
            options={'verbose_name': 'Vision et mission', 'verbose_name_plural': 'Vision et mission'},
        ),
        migrations.CreateModel(
            name='ProcedureProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voie_exportation', models.CharField(blank=True, choices=[('transport_terrestre', 'Transport Terrestre'), ('transport_maritime', 'Transport Maritime'), ('transport_aerien', 'Transport Aérien')], max_length=200, null=True)),
                ('formalisation', models.TextField()),
                ('dde', models.TextField()),
                ('autorisation', models.TextField()),
                ('redevance', models.TextField()),
                ('formalite_douane', models.TextField()),
                ('nb', models.TextField()),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('publier', 'Publier')], default='brouillon', max_length=10)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Est supprimé')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('certificat_conventionnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.certificationconventionnel')),
                ('certificat_technique', models.ManyToManyField(blank=True, related_name='procedures', to='core.certificationtechnique')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produit')),
            ],
            options={
                'verbose_name': "Procédure d'exportation",
            },
        ),
    ]
