# Generated by Django 4.2.7 on 2025-08-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ville_alter_produit_is_deleted_produit_villes'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='couleur',
            field=models.CharField(default='blue', max_length=20),
        ),
    ]
