# Generated by Django 4.2.7 on 2025-08-26 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_produit_couleur'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='adresse',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse complète'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='certifications',
            field=models.TextField(blank=True, null=True, verbose_name='Certifications obtenues'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='date_creation',
            field=models.DateField(blank=True, null=True, verbose_name="Date de création de l'entreprise"),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name="Description de l'entreprise"),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse email'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='image_couverture',
            field=models.ImageField(blank=True, null=True, upload_to='ImageEntreprise', verbose_name='Image de couverture'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='LogoEntreprise', verbose_name="Logo de l'entreprise"),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='nombre_employes',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Nombre d'employés"),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='secteur_activite',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Secteur d'activité"),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='site_web',
            field=models.URLField(blank=True, null=True, verbose_name='Site web'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='produit',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='core.entreprise', verbose_name='Entreprise productrice'),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='foire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entreprise_foire', to='core.foires'),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='nom',
            field=models.CharField(max_length=200, verbose_name="Nom de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='type_activite',
            field=models.CharField(max_length=200, verbose_name="Type d'activité"),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='ville',
            field=models.CharField(max_length=200, verbose_name='Ville'),
        ),
    ]
