# Generated by Django 4.2.7 on 2025-08-27 15:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_entreprise_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityfoire',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='detail',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='certificationconventionnel',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationtechnique',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='donneestrategique',
            name='detail',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='adresse',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Adresse complète'),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='certifications',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Certifications obtenues'),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="Description de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='faq',
            name='response',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='foires',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gouvernance',
            name='contenu',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='motdirecteur',
            name='contenu',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='procedureglobale',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='procedureproduct',
            name='autorisation',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='procedureproduct',
            name='dde',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='procedureproduct',
            name='formalisation',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='procedureproduct',
            name='formalite_douane',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='procedureproduct',
            name='nb',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='procedureproduct',
            name='redevance',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='description1',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='description2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quisommenous',
            name='detail',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='temoignage',
            name='contenu',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='valeur',
            name='contenu',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
