# Generated by Django 4.2.7 on 2025-08-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_activityfoire_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='pour_site',
            field=models.BooleanField(default=True),
        ),
    ]
