# Generated by Django 4.2.7 on 2025-09-02 15:32

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_visiteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse e-mail')),
                ('nom', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom (optionnel)')),
                ('prenom', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prénom (optionnel)')),
                ('pays', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays (optionnel)')),
                ('ville', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville (optionnel)')),
                ('secteur_activite', models.CharField(blank=True, max_length=200, null=True, verbose_name="Secteur d'activité (optionnel)")),
                ('est_actif', models.BooleanField(default=True, verbose_name='Abonnement actif')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('date_desinscription', models.DateTimeField(blank=True, null=True, verbose_name='Date de désinscription')),
                ('ip_inscription', models.GenericIPAddressField(blank=True, null=True, verbose_name="IP d'inscription")),
                ('source_inscription', models.CharField(default='site_web', max_length=100, verbose_name="Source d'inscription")),
            ],
            options={
                'verbose_name': 'Abonné Newsletter',
                'verbose_name_plural': 'Abonnés Newsletter',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du template')),
                ('sujet', models.CharField(max_length=200, verbose_name="Sujet de l'email")),
                ('contenu_html', ckeditor.fields.RichTextField(verbose_name='Contenu HTML')),
                ('contenu_texte', models.TextField(verbose_name='Contenu texte brut')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Template actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Template Newsletter',
                'verbose_name_plural': 'Templates Newsletter',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterEnvoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=200, verbose_name='Sujet envoyé')),
                ('nombre_destinataires', models.IntegerField(verbose_name='Nombre de destinataires')),
                ('nombre_envoyes', models.IntegerField(default=0, verbose_name="Nombre d'emails envoyés")),
                ('nombre_erreurs', models.IntegerField(default=0, verbose_name="Nombre d'erreurs")),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('erreur', 'Erreur')], default='en_cours', max_length=20, verbose_name="Statut de l'envoi")),
                ('details_erreur', models.TextField(blank=True, null=True, verbose_name='Détails des erreurs')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.newslettertemplate', verbose_name='Template utilisé')),
            ],
            options={
                'verbose_name': 'Envoi Newsletter',
                'verbose_name_plural': 'Envois Newsletter',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
