# Generated by Django 4.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_newsletter_newslettertemplate_newsletterenvoi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interprofession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'interprofession")),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code (identifiant unique)')),
                ('slug', models.SlugField(blank=True, max_length=220, null=True)),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('publier', 'Publier')], default='brouillon', max_length=10)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Est supprimé')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Interprofession',
                'verbose_name_plural': 'Interprofessions',
            },
        ),
        migrations.CreateModel(
            name='PersonnelInterprofession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=150, verbose_name='Prénom')),
                ('localisation', models.CharField(blank=True, max_length=200, null=True, verbose_name='Localisation')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Adresse email')),
                ('poste', models.CharField(blank=True, max_length=200, null=True, verbose_name="Poste dans l'interprofession")),
                ('profession', models.CharField(blank=True, max_length=200, null=True, verbose_name='Profession')),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('publier', 'Publier')], default='brouillon', max_length=10)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Est supprimé')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('interprofession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnels', to='core.interprofession', verbose_name='Interprofession')),
            ],
            options={
                'verbose_name': 'Personnel interprofession',
                'verbose_name_plural': 'Personnels des interprofessions',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
