# Generated by Django 4.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_projet_etapeprojet'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieStatistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True)),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Est supprimé')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Catégorie de statistique',
                'verbose_name_plural': 'Catégories de statistiques',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Statistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(verbose_name='Année')),
                ('mois', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], null=True, verbose_name='Mois (vide = statistique annuelle)')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre / Libellé')),
                ('valeur', models.DecimalField(decimal_places=2, help_text='Valeur numérique de la statistique', max_digits=18, verbose_name='Valeur')),
                ('unite', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unité (ex: tonnes, GNF, %)')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Est supprimé')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statistiques', to='core.categoriestatistique', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Statistique',
                'verbose_name_plural': 'Statistiques',
                'ordering': ['-annee', 'mois', 'ordre', 'titre'],
            },
        ),
    ]
