# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_categoriestatistique_statistique'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='responsable_nom',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom du responsable du projet'),
        ),
        migrations.AddField(
            model_name='projet',
            name='responsable_poste',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Poste du responsable'),
        ),
        migrations.RemoveField(
            model_name='projet',
            name='attribue_a',
        ),
    ]
