# Generated by Django 4.2

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_projet_responsable_remplace_attribue_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapeprojet',
            name='pourcentage',
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Valeur entre 0 et 100 (optionnel)",
                null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                verbose_name="Pourcentage d'avancement (%)"
            ),
        ),
    ]
