# Generated by Django 4.2

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_etapeprojet_pourcentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestationCommerciale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=280, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('statut_global', models.CharField(choices=[('bientot_prevu', 'Bientôt prévu'), ('a_postuler', 'À postuler'), ('selection_terminee', 'Sélection terminée'), ('manifestation_terminee', 'Manifestation terminée')], default='bientot_prevu', max_length=30, verbose_name='Statut global')),
                ('statut_publication', models.CharField(choices=[('brouillon', 'Brouillon'), ('publier', 'Publier')], default='brouillon', max_length=10, verbose_name='Publication (Front Office)')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('lieu', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lieu')),
                ('pays', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Est supprimé')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Manifestation commerciale',
                'verbose_name_plural': 'Manifestations commerciales',
                'ordering': ['-date_debut', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EtapeManifestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Ordre (1 à 4)')),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'étape")),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Est supprimé')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('manifestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='core.manifestationcommerciale', verbose_name='Manifestation')),
            ],
            options={
                'verbose_name': 'Étape de manifestation',
                'verbose_name_plural': 'Étapes de manifestation',
                'ordering': ['manifestation', 'ordre'],
                'unique_together': {('manifestation', 'ordre')},
            },
        ),
        migrations.CreateModel(
            name='CandidatureManifestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(blank=True, max_length=200, null=True, verbose_name="Nom de l'entreprise")),
                ('email_contact', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email du contact')),
                ('telephone_contact', models.CharField(blank=True, max_length=30, null=True, verbose_name='Téléphone')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('statut_metier', models.CharField(choices=[('a_postuler', 'À postuler'), ('selectionnee', 'Sélectionnée'), ('refusee', 'Refusée'), ('desistee', 'Désistée'), ('ayant_participe', 'Ayant participé')], default='a_postuler', max_length=20, verbose_name='Statut métier (processus)')),
                ('statut_back_office', models.CharField(choices=[('brouillon', 'Brouillon'), ('publier', 'Publié')], default='brouillon', max_length=10, verbose_name='Statut back office')),
                ('date_candidature', models.DateTimeField(auto_now_add=True, verbose_name='Date de candidature')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Est supprimé')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatures_manifestation', to='core.entreprise', verbose_name='Entreprise')),
                ('etape_actuelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures_etape', to='core.etapemanifestation', verbose_name='Étape actuelle')),
                ('manifestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='core.manifestationcommerciale', verbose_name='Manifestation')),
            ],
            options={
                'verbose_name': 'Candidature à une manifestation',
                'verbose_name_plural': 'Candidatures aux manifestations',
                'ordering': ['manifestation', '-date_candidature'],
            },
        ),
    ]
