# Generated by Django 4.2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_manifestation_commerciale'),
    ]

    operations = [
        # Table core_candidatureetapehistorique déjà présente en base : on met à jour uniquement l'état des migrations
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='CandidatureEtapeHistorique',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('date_entree', models.DateTimeField(auto_now_add=True, verbose_name="Date d'entrée à l'étape")),
                        ('date_sortie', models.DateTimeField(blank=True, null=True, verbose_name="Date de sortie de l'étape")),
                        ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_etapes', to='core.candidaturemanifestation', verbose_name='Candidature')),
                        ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_candidatures', to='core.etapemanifestation', verbose_name='Étape')),
                    ],
                    options={
                        'verbose_name': 'Historique étape candidature',
                        'verbose_name_plural': 'Historiques étapes candidatures',
                        'ordering': ['candidature', 'date_entree'],
                    },
                ),
            ],
            database_operations=[],
        ),
        migrations.CreateModel(
            name='CandidatureDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('accepte', 'Accepter'), ('refuse', 'Refuser')], max_length=10, verbose_name='Décision')),
                ('decided_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de la décision')),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='core.candidaturemanifestation', verbose_name='Candidature')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_candidature', to=settings.AUTH_USER_MODEL, verbose_name='Admin responsable')),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions_candidatures', to='core.etapemanifestation', verbose_name='Étape au moment de la décision')),
            ],
            options={
                'verbose_name': 'Décision candidature',
                'verbose_name_plural': 'Décisions candidatures',
                'ordering': ['-decided_at'],
            },
        ),
    ]
