# Generated by Django 4.2.7 on 2026-02-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_entreprise_site_web_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapemanifestation',
            name='date_debut',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début'),
        ),
        migrations.AddField(
            model_name='etapemanifestation',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
    ]
