# Generated by Django 4.2.7 on 2026-02-09 13:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_create_candidature_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidaturemanifestation',
            name='a_code_nif',
            field=models.BooleanField(default=False, verbose_name='Avez-vous un code NIF à jour ?'),
        ),
        migrations.AddField(
            model_name='candidaturemanifestation',
            name='a_rccm',
            field=models.BooleanField(default=False, verbose_name='Avez-vous un RCCM ?'),
        ),
        migrations.AddField(
            model_name='candidaturemanifestation',
            name='certifications',
            field=models.TextField(blank=True, help_text="Liste des certifications obtenues par l'entreprise", null=True, verbose_name="Certifications de l'entreprise"),
        ),
        migrations.AddField(
            model_name='candidaturemanifestation',
            name='date_creation_entreprise',
            field=models.DateField(blank=True, null=True, verbose_name="Date de création de l'entreprise"),
        ),
        migrations.AddField(
            model_name='candidaturemanifestation',
            name='domaine_activite',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Domaine d'activité"),
        ),
        migrations.AddField(
            model_name='candidaturemanifestation',
            name='nombre_manifestations_participees',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='À combien de manifestations commerciales avez-vous déjà participé ?'),
        ),
        migrations.AddField(
            model_name='candidaturemanifestation',
            name='nombre_personnes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Nombre de personnes dans l'entreprise"),
        ),
        migrations.AddField(
            model_name='candidaturemanifestation',
            name='peut_se_financer',
            field=models.BooleanField(default=False, verbose_name='Pouvez-vous vous financer ?'),
        ),
        migrations.AddField(
            model_name='candidaturemanifestation',
            name='produits_entreprise',
            field=models.TextField(blank=True, help_text="Liste des produits proposés par l'entreprise", null=True, verbose_name="Produits de l'entreprise"),
        ),
        migrations.AddField(
            model_name='candidaturemanifestation',
            name='responsable_entreprise',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Responsable de l'entreprise"),
        ),
        migrations.AddField(
            model_name='candidaturemanifestation',
            name='siege_social',
            field=models.TextField(blank=True, null=True, verbose_name="Siège social de l'entreprise"),
        ),
        migrations.AddField(
            model_name='candidaturemanifestation',
            name='type_entreprise',
            field=models.CharField(blank=True, help_text='Ex: SARL, SA, EURL, etc.', max_length=100, null=True, verbose_name="Type d'entreprise"),
        ),
        migrations.AddField(
            model_name='manifestationcommerciale',
            name='conditions_de_participation',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Conditions et critères requis pour participer à cette manifestation', null=True, verbose_name='Conditions de participation'),
        ),
    ]
