# Generated by Django 4.2.7 on 2026-02-09 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_conditions_participation_and_candidature_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True, verbose_name='Nom du type de produit')),
                ('slug', models.SlugField(blank=True, max_length=191, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('icone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Icône (classe FontAwesome)')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('publier', 'Publier')], default='publier', max_length=10)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Est supprimé')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Type de produit',
                'verbose_name_plural': 'Types de produits',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ProduitEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('description_courte', models.TextField(help_text='Maximum 500 caractères', max_length=500, verbose_name='Description courte')),
                ('image', models.ImageField(upload_to='ProduitsEntreprise', verbose_name='Image du produit')),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('publier', 'Publier')], default='brouillon', max_length=10)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Est supprimé')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_entreprise', to='core.entreprise', verbose_name='Entreprise')),
                ('type_produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='core.typeproduit', verbose_name='Type de produit')),
            ],
            options={
                'verbose_name': 'Produit entreprise',
                'verbose_name_plural': 'Produits entreprises',
                'ordering': ['-created_at'],
            },
        ),
    ]
