# Generated by Django 4.2.7 on 2026-02-10 00:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_create_type_produit_and_produit_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='interprofession',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text="Description détaillée de l'interprofession", null=True, verbose_name='Description'),
        ),
    ]
