# Generated by Django 4.2.7 on 2026-04-24 12:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_interprofession_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureExportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('description', ckeditor.fields.RichTextField()),
                ('icone', models.CharField(help_text="Chemin statique de l'icone, ex: assets/img/icon/route.png", max_length=255)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('publier', 'Publier')], default='brouillon', max_length=10)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Est supprimé')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': "Infrastructure d'exportation",
                'verbose_name_plural': "Infrastructures d'exportation",
                'ordering': ['ordre', 'created_at'],
            },
        ),
    ]
