# Generated by Django 4.2.7 on 2026-04-24 12:53

from django.db import migrations


def seed_infrastructures(apps, schema_editor):
    InfrastructureExportation = apps.get_model('core', 'InfrastructureExportation')
    initial_data = [
        {
            "titre": "Transport Terrestre",
            "description": "Une solution sur mesure pour faciliter l’exportation vers les pays voisins via le transport terrestre.",
            "icone": "assets/img/icon/route.png",
            "ordre": 1,
        },
        {
            "titre": "Transport Maritime",
            "description": "Idéal pour l’exportation de grandes quantités de marchandises par voie maritime.",
            "icone": "assets/img/icon/bateau.png",
            "ordre": 2,
        },
        {
            "titre": "Transport Aérien",
            "description": "Convient aux exportations urgentes et aux marchandises à forte valeur ajoutée.",
            "icone": "assets/img/icon/avion.png",
            "ordre": 3,
        },
    ]

    for item in initial_data:
        InfrastructureExportation.objects.update_or_create(
            titre=item["titre"],
            defaults={
                "description": item["description"],
                "icone": item["icone"],
                "ordre": item["ordre"],
                "status": "publier",
                "is_deleted": False,
            },
        )


def unseed_infrastructures(apps, schema_editor):
    InfrastructureExportation = apps.get_model('core', 'InfrastructureExportation')
    InfrastructureExportation.objects.filter(
        titre__in=["Transport Terrestre", "Transport Maritime", "Transport Aérien"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_infrastructureexportation'),
    ]

    operations = [
        migrations.RunPython(seed_infrastructures, unseed_infrastructures),
    ]
